# Site settings
title: Wavio
email: marvin@wavio.co
description: > # this means to ignore newlines until "baseurl:"
  Wavio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wavio.co" # the base hostname & protocol for your site
twitter_username: MarvinNazari
github_username:  wavio

# Build settings
markdown: kramdown
